# from https://github.com/PHPirates/travis-ci-latex-pdf/blob/master/4-texlive/.travis.yml
language: shell
os: linux
dist: bionic

# Dependency of the minted package
#before_install:
# - sudo apt-get install python-pygments
install:
  - source ./texlive/texlive_install.sh
  - mkdir -p ~/.ssh
  - echo '-----BEGIN OPENSSH PRIVATE KEY-----' > ~/.ssh/id_rsa
  - echo $SSH_KEY >> ~/.ssh/id_rsa
  - echo '-----END OPENSSH PRIVATE KEY-----' >> ~/.ssh/id_rsa
  - chmod og= ~/.ssh/id_rsa
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
# Change working directory so including files will work
before_script:
  - cd $TRAVIS_BUILD_DIR/

addons:
  apt:
    packages:
      - python-pygments
    update: true

script:
  - set -e
  - make -B

  - git remote -v
  - git remote set-url origin git@github.com:vlstill/phd-thesis.git
  - git remote -v
  - git checkout --orphan gh-pages
  - git reset --hard
  - printf '<html><head><meta http-equiv="refresh" content="0; url=https://vlstill.github.io/phd-thesis/thesis.pdf"></head><body><a href="https://vlstill.github.io/phd-thesis/thesis.pdf">Download PDF</a></body></html>' > index.html
  - printf '[Download PDF](https://vlstill.github.io/phd-thesis/thesis.pdf)' > index.md
  - git stage thesis.pdf list-of-publications.pdf index.html index.md
  - git commit -a -m "Update PDF"
  - if test "$TRAVIS_BRANCH" = master; then git push --set-upstream origin gh-pages --force; fi

  # You can also pass arguments to texliveonfly:
#  - texliveonfly --arguments='-shell-escape' main.tex
